trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: MavenBuild
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'package'

- stage: Deploy
  jobs:
  - job: FakeDeploy
    steps:
    - script: echo "Deploy realizado"