trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: MavenBuild
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - script: echo "Deploy realizado"